version: '3.8'

services:
  postgres_proposal:
    image: postgres
    container_name: postgres-proposal
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: proposaldb
      POSTGRES_USER: viana
      POSTGRES_PASSWORD: docker123
    ports:
      - "5433:5432"
    networks:
      - proposal-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - proposal-network

  web-proposal:
    image: matheuspieropan/proposta-web
    container_name: web-proposal-container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - postgres_proposal
    networks:
      - proposal-network

networks:
  proposal-network:
    driver: bridge
