server:
  port: 8081
  servlet:
    context-path: '/credit-proposal/'

spring:
  application:
    name: credit-proposal-service
  datasource:
    url: jdbc:postgresql://localhost:5433/proposaldb
    username: viana
    password: docker123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
    show-sql: true
