server:
  port: 8081
  servlet:
    context-path: '/credit-proposal/'

spring:
  application:
    name: credit-proposal-service
  datasource:
    url: jdbc:postgresql://localhost:5433/proposaldb
    username: viana
    password: docker123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
    show-sql: true
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdb
    baselineOnMigrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  proposal-pending:
    exchange: proposal-pending-exchange

logging:
  level:
    com.macielviana.proposal: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO